### ISSUE TITLE
Compatibility with Contao 3.5 and Isotope 2.2.5

### ISSUE THREAD

**Issue by jankout** [inszenium/isotope-export#2]
I have tried to install your extension with composer but I cannot do it because your extension is not ready for Contao 3.5... Could you change the versions of compatible Contaos, please? That could resolve the problem I think. Thank you. 

Thank you. Best wishes, Jan

https://github.com/isotope/core/issues/196#issuecomment-117058160

**Comment by katgirl** [comment]
see [2.0.1](https://github.com/inszenium/isotope-export/tree/2.0.1)
