### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by mirkokienle** [inszenium/isotope-export#3]
```
  - Installing inszenium/isotope-export (2.0.1): Downloading (100%)

                                    
  [ErrorException]                  
  copy(): Filename cannot be empty  
```

**Comment by katgirl** [comment]
wie kann ich das reproduzieren, bei mir läuft es

**Comment by mirkokienle** [comment]
Auf drei unterschiedlichen Servern auf zwei Hosts mit isotope-Installation getestet; gleiches Resultat auf allen.

**Comment by katgirl** [comment]
aber wie? Contao Version, Isotope Version installtion über composer auf Komandozeile oder über das Plugin?

**Comment by mirkokienle** [comment]
Contao 3.5.17 & 3.5.24; Isotope 2.4.1; Composer als normale Paketverwaltung als eigenständiger Prozess

**Comment by katgirl** [comment]
nimm bitte mal den dev zweig da habe ich den Composer mal geändert

**Comment by mirkokienle** [comment]
OK, Installation von 1.0.3 ist ohne Fehlermeldungen abgelaufen. Aber ich sehe keine Exportfunktion und auf der Contaoinstallation auf FTP ist auch kein neues Modul installiert.

**Comment by katgirl** [comment]
ist mit Version 2.0.2 behoben
